#-------------------------------
# General Site Settings
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Coderon"
googleAnalytics = "14189624953" # Add your identifier. For example UA-99631805-1.


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  logo_dark = ""
  description = "Coderon is a super modern and unique Hugo blog theme"


#-------------------------------
# Color Scheme:
[params.color_scheme]
  default = "dark" # Default theme applied on the first visit (options: "light" or "dark")
  toggle = true # Enable theme toggle

# Enables or disables the theme toggle functionality:
# - true: Users can switch between light and dark modes using a toggle button.
#          The site will remember their choice for future visits.
# - false: The theme will always use the default mode specified above,
#          and the toggle button will not be displayed.


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1


  [[menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = 3

  [[menu.main]]
    name = "Pages"
    weight = 4
    hasChildren = true

  [[menu.main]]
    parent = "Pages"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    parent = "Pages"
    name = "Contact"
    url = "/contact/"
    weight = 2

  [[menu.main]]
    parent = "Pages"
    name = "Elements"
    url = "/elements/"
    weight = 3


#-------------------------------
# Author Settings
[params.author]
  author_name = "Marcin"
  author_avatar = "https://placehold.co/120x120"








#-------------------------------
# Blog Section
[params.blog]
  enable = true
  blog_title = "The Shell Log"


#-------------------------------
# Pagination settings:
[pagination]
  pagerSize = 4












#-------------------------------
# Footer Settings
[params.footer]
  footer_description = "A place where I learn, break things, and understand how they really work. This blog is my personal cybersecurity notebook — focused on Hack The Box, enumeration, and building real skills. Every post reflects what I’m learning right now, including mistakes, lessons, and better approaches."


#-------------------------------
# Social Settings
[[params.social]]
  icon = "fa-brands fa-x-twitter"
  name = "Twitter"
  link = "https://twitter.com"

[[params.social]]
  icon = "fa-brands fa-facebook"
  name = "Facebook"
  link = "https://facebook.com"

[[params.social]]
  icon = "fa-brands fa-mastodon"
  name = "Mastodon"
  link = "https://mastodon.social"

[[params.social]]
  icon = "fa-brands fa-reddit-alien"
  name = "Reddit"
  link = "https://reddit.com"

[[params.social]]
  icon = "fa-brands fa-github"
  name = "Github"
  link = "https://github.com"

[[params.social]]
  icon = "fa-solid fa-rss"
  name = "Rss"
  link = "/index.xml"

# Example of adding a new link to the sidebar and footer:
# [[params.social]]
#   icon = "fa-brands fa-youtube"
#   name = "Youtube"
#   link = "https://youtube.com"

# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
[params.contact]
  form_id = "meerbodr" # Add your form_id
  button_text = "Send Now"

  # NOTE
  # Coderon comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Comment Section (Disqus)
[params.disqus]
  enable = true
  disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test
  disqus_title = "Start the conversation"
  disqus_button_text = "Show Comments"


[taxonomies]
  tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


  [markup.tableOfContents]
    startLevel = 2
    ordered = true
    endLevel = 3


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
